apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-frontend
spec:
  selector:
    matchLabels:
      app: catalogue
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogue
        tier: frontend
        track: stable
    spec:
      containers:
        - name: catalogue-frontend
          image: ajaira/catalogue-frontend:v6

---
kind: Service
apiVersion: v1
metadata:
  name: catalogue-frontend
spec:
  selector:
    app: catalogue
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
